// AUTO-GENERATED by scripts/generate-content-map.js — do not edit manually
import type { Block } from "@blocknote/core";

import chapter_0 from "@/content/physics/electric-charges-and-fields/chapter.json";
import chapter_1 from "@/content/physics/electrostatic-potential-and-capacitance/chapter.json";

export const AUTO_BLOCKS_MAP: Record<string, { subject: string; loader: () => Promise<{ default: Block[] }> }> = {
  "electric-charges-and-fields": { subject: "physics", loader: () => Promise.resolve({ default: chapter_0 as Block[] }) },
  "electrostatic-potential-and-capacitance": { subject: "physics", loader: () => Promise.resolve({ default: chapter_1 as Block[] }) },
};

// Sections are still manually maintained in content-loader.ts
// (they come from chapter metadata, not JSON files)
