import { Callout } from "@/components/content/Callout";
import { KeyPoint } from "@/components/content/KeyPoint";
import { Expandable } from "@/components/content/Expandable";
import { Formula, FormulaBlock } from "@/components/content/Formula";
import { ProblemSolution } from "@/components/content/ProblemSolution";
import { Stepper } from "@/components/content/Stepper";
import { FormulaCard } from "@/components/content/FormulaCard";
import { Highlight } from "@/components/content/Highlight";
import { SpeedTricks } from "@/components/content/SpeedTricks";
import { FunctionGraph } from "@/components/content/maths/FunctionGraph";
import { CircleDiagram, ParabolaFocus, ParabolaFour, EllipseDiagram, HyperbolaDiagram } from "@/components/content/conic/ConicDiagrams";

export default function ConicSectionsChapter() {
  return (
    <>
      <h2 id="h-cone">10.2 Sections of a Cone</h2>
      <p>
        A <strong>right circular double cone</strong> is generated by rotating a line (generator) about
        a fixed vertical axis. The two nappes meet at the <Highlight>vertex</Highlight>.
      </p>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/d/d3/Conic_sections_with_plane.svg"
          alt="Double cone intersected by a plane producing circle, ellipse, parabola and hyperbola depending on angle beta vs alpha"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs leading-relaxed text-muted-foreground text-center">
          Real figure — double cone cut by a plane at different angles β vs α: <strong>circle</strong> (β=90°), <strong>ellipse</strong> (α&lt;β&lt;90°), <strong>parabola</strong> (β=α), <strong>hyperbola</strong> (β&lt;α). Source:{" "}
          <a href="https://commons.wikimedia.org/wiki/File:Conic_sections_with_plane.svg" target="_blank" rel="noreferrer" className="underline">
            Wikimedia Commons / Pbroks13 (CC0)
          </a>{" "}
          — see NCERT Fig 11.1–11.7. Full PDF:{" "}
          <a href="https://ncert.nic.in/textbook/pdf/kemh111.pdf" target="_blank" rel="noreferrer" className="underline">
            kemh111.pdf
          </a>
          .
        </figcaption>
      </figure>
      <Callout type="important" title="How the Plane Cuts the Cone">
        <table>
          <thead>
            <tr>
              <th>Angle of plane</th>
              <th>Curve obtained</th>
              <th>Condition</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Perpendicular to axis</td>
              <td><strong>Circle</strong></td>
              <td>Plane ⊥ axis</td>
            </tr>
            <tr>
              <td>Tilted, cuts one nappe fully</td>
              <td><strong>Ellipse</strong></td>
              <td>α &lt; β (angle of plane &lt; generator angle)</td>
            </tr>
            <tr>
              <td>Parallel to a generator</td>
              <td><strong>Parabola</strong></td>
              <td>α = β</td>
            </tr>
            <tr>
              <td>Cuts both nappes</td>
              <td><strong>Hyperbola</strong></td>
              <td>α &gt; β</td>
            </tr>
            <tr>
              <td>Through the vertex</td>
              <td><strong>Degenerate cases</strong></td>
              <td>Point, line, or pair of lines</td>
            </tr>
          </tbody>
        </table>
      </Callout>

      <h2 id="h-circle">10.3 Circle</h2>
      <Callout type="important" title="Definition: Circle">
        A <strong>circle</strong> is the set of all points in a plane that are at a fixed distance (the{" "}
        <strong>radius</strong> r) from a fixed point (the <strong>centre</strong> C(h, k)).
      </Callout>
      <CircleDiagram />

      <h3>Equation of a Circle</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Form (Centre-Radius)</p>
        <FormulaBlock latex={String.raw`(x - h)^2 + (y - k)^2 = r^2`} />
        <p className="text-sm text-muted-foreground mt-2">Centre = (h, k), Radius = r</p>
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">Centre at Origin</p>
        <FormulaBlock latex={String.raw`x^2 + y^2 = r^2`} />
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">General Form</p>
        <FormulaBlock latex={String.raw`x^2 + y^2 + 2gx + 2fy + c = 0`} />
        <p className="text-sm text-muted-foreground mt-2">Centre = (−g, −f), Radius = √(g² + f² − c)</p>
      </FormulaCard>
      <KeyPoint>
        The general form expands as (x + g)² + (y + f)² = g² + f² − c. For a valid circle, we need{" "}
        <Highlight>g² + f² − c &gt; 0</Highlight>.
      </KeyPoint>

      <SpeedTricks>
        <Callout type="tip" title="Quick centre from general form">
          Read off g and f from the coefficients of x and y (halve and negate). Centre = (−g, −f). No need to complete the square every time.
        </Callout>
        <Callout type="tip" title="Radius check">
          From general form: r² = g² + f² − c. If this is ≤ 0, the equation has no real circle — a common MCQ trap.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-circle" title="Examples — Circle">
        <ProblemSolution problemNumber="Example 1">
          <ProblemSolution.Problem>
            <p>Find the equation of the circle with centre (3, −2) and radius 4.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <FormulaBlock latex={String.raw`(x - 3)^2 + (y + 2)^2 = 16`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 2">
          <ProblemSolution.Problem>
            <p>Find the centre and radius of x² + y² − 6x + 4y − 12 = 0.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify g, f, c", description: <Formula>{String.raw`2g = -6 \to g = -3;\ \ 2f = 4 \to f = 2;\ \ c = -12`}</Formula> },
                { label: "Centre", description: <Formula>{String.raw`(-g, -f) = (3, -2)`}</Formula> },
                { label: "Radius", description: <Formula>{String.raw`r = \sqrt{9+4+12} = \sqrt{25} = 5`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-parabola">10.4 Parabola</h2>
      <Callout type="important" title="Definition: Parabola">
        A <strong>parabola</strong> is the set of all points in a plane that are equidistant from a fixed
        point (<Highlight>focus</Highlight>) and a fixed line (<Highlight>directrix</Highlight>).
      </Callout>
      <ParabolaFocus />
      <KeyPoint title="Key Terms">
        <ul>
          <li><strong>Focus (S):</strong> the fixed point.</li>
          <li><strong>Directrix:</strong> the fixed line.</li>
          <li><strong>Vertex:</strong> midpoint of the perpendicular from focus to directrix.</li>
          <li><strong>Axis:</strong> the line through the focus perpendicular to the directrix.</li>
          <li><strong>Latus Rectum:</strong> the chord through the focus perpendicular to the axis. Length ={" "}
            <Highlight>4a</Highlight>.</li>
        </ul>
      </KeyPoint>

      <h3>Standard Equations of Parabola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Four Standard Forms</p>
        <table>
          <thead>
            <tr>
              <th>Equation</th>
              <th>Opens</th>
              <th>Focus</th>
              <th>Directrix</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>y² = 4ax</td>
              <td>Right</td>
              <td>(a, 0)</td>
              <td>x = −a</td>
            </tr>
            <tr>
              <td>y² = −4ax</td>
              <td>Left</td>
              <td>(−a, 0)</td>
              <td>x = a</td>
            </tr>
            <tr>
              <td>x² = 4ay</td>
              <td>Up</td>
              <td>(0, a)</td>
              <td>y = −a</td>
            </tr>
            <tr>
              <td>x² = −4ay</td>
              <td>Down</td>
              <td>(0, −a)</td>
              <td>y = a</td>
            </tr>
          </tbody>
        </table>
      </FormulaCard>
      <ParabolaFour />
      <p>Here a is the distance from the vertex to the focus (and from the vertex to the directrix).</p>

      <FunctionGraph
        curves={[
          { fn: (x) => 2 * Math.sqrt(x), from: 0, to: 5 },
          { fn: (x) => -2 * Math.sqrt(x), from: 0, to: 5 },
        ]}
        points={[{ x: 1, y: 0 }]}
        xMin={-3} xMax={6} yMin={-5} yMax={5}
        xTicks={[{ at: 1, label: "S(1,0)" }]}
        caption="y² = 4x — parabola opening right, a = 1, focus at (1, 0)"
      />

      <FunctionGraph
        curves={[
          { fn: (x) => -2 * Math.sqrt(x), from: 0, to: 5 },
          { fn: (x) => 2 * Math.sqrt(x), from: 0, to: 5 },
        ]}
        points={[{ x: -1, y: 0 }]}
        xMin={-6} xMax={3} yMin={-5} yMax={5}
        xTicks={[{ at: -1, label: "S(−1,0)" }]}
        caption="y² = −4x — parabola opening left, a = 1, focus at (−1, 0)"
      />

      <SpeedTricks>
        <Callout type="tip" title="Remember the four forms">
          y² = ±4ax opens horizontally (± gives left/right). x² = ±4ay opens vertically (± gives up/down). The variable that is <em>squared</em> determines the direction.
        </Callout>
        <Callout type="tip" title="Latus Rectum = 4a always">
          For all four standard parabolas, the latus rectum length is 4a. Just read a from the equation — no memorising separate formulas.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-parabola" title="Examples — Parabola">
        <ProblemSolution problemNumber="Example 3">
          <ProblemSolution.Problem>
            <p>Find the focus, directrix, and latus rectum of y² = 12x.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Compare with y² = 4ax", description: <Formula>{String.raw`4a = 12 \to a = 3`}</Formula> },
                { label: "Focus", description: "(a, 0) = (3, 0)" },
                { label: "Directrix", description: "x = −a = −3" },
                { label: "Latus Rectum", description: "4a = 12" },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 4">
          <ProblemSolution.Problem>
            <p>Find the equation of the parabola with focus (0, 4) and directrix y = −4.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p>Focus is above the directrix on the y-axis, so the parabola opens upward.</p>
            <Stepper
              steps={[
                { label: "Identify a", description: "Distance from vertex (0,0) to focus = a = 4" },
                { label: "Form", description: <Formula>{String.raw`x^2 = 4ay = 4(4)y = 16y`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`x^2 = 16y`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-ellipse">10.5 Ellipse</h2>
      <Callout type="important" title="Definition: Ellipse">
        An <strong>ellipse</strong> is the set of all points in a plane such that the{" "}
        <Highlight>sum of distances from two fixed points (foci)</Highlight> is a constant.
      </Callout>
      <EllipseDiagram />

      <h3>Standard Equations of Ellipse</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Forms</p>
        <table>
          <thead>
            <tr>
              <th>Equation</th>
              <th>Major Axis</th>
              <th>Foci</th>
              <th>Vertices</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>x²/a² + y²/b² = 1 &nbsp;(a &gt; b)</td>
              <td>Along x-axis</td>
              <td>(±c, 0)</td>
              <td>(±a, 0)</td>
            </tr>
            <tr>
              <td>x²/b² + y²/a² = 1 &nbsp;(a &gt; b)</td>
              <td>Along y-axis</td>
              <td>(0, ±c)</td>
              <td>(0, ±a)</td>
            </tr>
          </tbody>
        </table>
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">Key Relations</p>
        <FormulaBlock latex={String.raw`c^2 = a^2 - b^2`} />
        <FormulaBlock latex={String.raw`e = \frac{c}{a}, \quad 0 < e < 1`} />
        <FormulaBlock latex={String.raw`\text{Latus Rectum} = \frac{2b^2}{a}`} />
        <p className="text-sm text-muted-foreground mt-2">a = semi-major axis, b = semi-minor axis, c = distance from centre to focus, e = eccentricity</p>
      </FormulaCard>

      <KeyPoint title="Properties of Ellipse">
        <ul>
          <li><strong>Eccentricity:</strong> 0 &lt; e &lt; 1 (e = 0 gives a circle).</li>
          <li><strong>Vertices:</strong> endpoints of the major axis — (±a, 0) or (0, ±a).</li>
          <li><strong>Major axis length:</strong> 2a. <strong>Minor axis length:</strong> 2b.</li>
          <li><strong>Latus Rectum:</strong> chord through a focus perpendicular to the major axis. Length = 2b²/a.</li>
          <li><Highlight>a² = b² + c²</Highlight> — the larger of a² and b² equals the sum of the other two.</li>
        </ul>
      </KeyPoint>

      <FunctionGraph
        curves={[
          { fn: (x) => 3 * Math.sqrt(1 - (x * x) / 25), from: -5, to: 5 },
          { fn: (x) => -3 * Math.sqrt(1 - (x * x) / 25), from: -5, to: 5 },
        ]}
        points={[{ x: 4, y: 0, filled: false }, { x: -4, y: 0, filled: false }]}
        xMin={-7} xMax={7} yMin={-5} yMax={5}
        xTicks={[{ at: -4, label: "−c" }, { at: 4, label: "c" }]}
        caption="x²/25 + y²/9 = 1 — a = 5, b = 3, c = 4, e = 4/5"
      />

      <SpeedTricks>
        <Callout type="tip" title="Which is a, which is b?">
          Always: a &gt; b. If the larger denominator is under x², major axis is horizontal. If under y², vertical. Don&apos;t assume a is always under x².
        </Callout>
        <Callout type="tip" title="a² = b² + c² (not c² = a² + b²)">
          Common exam trap: for ellipse, c² = a² − b² (so a² = b² + c²). For hyperbola, c² = a² + b². The roles of a and c are different.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-ellipse" title="Examples — Ellipse">
        <ProblemSolution problemNumber="Example 5">
          <ProblemSolution.Problem>
            <p>Find the equation of the ellipse with foci (±3, 0) and vertices (±5, 0).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a and c", description: <Formula>{String.raw`a = 5, c = 3`}</Formula> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = a^2 - c^2 = 25 - 9 = 16 \to b = 4`}</Formula> },
                { label: "Equation", description: <><Formula>{String.raw`\frac{x^2}{25} + \frac{y^2}{16} = 1`}</Formula> — major axis along the x-axis</> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{25} + \frac{y^2}{16} = 1`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 6">
          <ProblemSolution.Problem>
            <p>Find the eccentricity, foci, and latus rectum of x²/16 + y²/9 = 1.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a^2 = 16 \to a = 4;\ \ b^2 = 9 \to b = 3`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c^2 = 16 - 9 = 7 \to c = \sqrt 7`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{\sqrt 7}{4}`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(\pm\sqrt 7, 0)`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2(9)}{4} = \frac{9}{2}`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-hyperbola">10.6 Hyperbola</h2>
      <Callout type="important" title="Definition: Hyperbola">
        A <strong>hyperbola</strong> is the set of all points in a plane such that the{" "}
        <Highlight>difference of distances from two fixed points (foci)</Highlight> is a constant.
      </Callout>
      <HyperbolaDiagram />

      <h3>Standard Equation of Hyperbola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Form</p>
        <FormulaBlock latex={String.raw`\frac{x^2}{a^2} - \frac{y^2}{b^2} = 1`} />
        <p className="text-sm text-muted-foreground mt-2">Transverse axis along x-axis. Centre at origin.</p>
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">Key Relations</p>
        <FormulaBlock latex={String.raw`c^2 = a^2 + b^2`} />
        <FormulaBlock latex={String.raw`e = \frac{c}{a} > 1`} />
        <FormulaBlock latex={String.raw`\text{Latus Rectum} = \frac{2b^2}{a}`} />
      </FormulaCard>

      <KeyPoint title="Properties of Hyperbola">
        <ul>
          <li><strong>Transverse axis:</strong> the axis passing through the foci. Length = 2a.</li>
          <li><strong>Conjugate axis:</strong> perpendicular to transverse axis through the centre. Length = 2b.</li>
          <li><strong>Vertices:</strong> (±a, 0) — endpoints of the transverse axis.</li>
          <li><strong>Foci:</strong> (±c, 0) where c² = a² + b².</li>
          <li><strong>Eccentricity:</strong> e = c/a &gt; 1 (always greater than 1 for hyperbola).</li>
          <li><strong>Asymptotes:</strong> y = ±(b/a)x — the hyperbola approaches these lines at infinity.</li>
        </ul>
      </KeyPoint>

      <h3>Equilateral Hyperbola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Equilateral (Rectangular) Hyperbola</p>
        <FormulaBlock latex={String.raw`x^2 - y^2 = a^2 \quad \text{(when } a = b\text{)}`} />
        <p className="text-sm text-muted-foreground mt-2">Eccentricity = √2. Asymptotes are perpendicular (y = ±x).</p>
      </FormulaCard>

      <FunctionGraph
        curves={[
          { fn: (x) => 3 * Math.sqrt((x * x) / 25 - 1), from: 5, to: 8 },
          { fn: (x) => -3 * Math.sqrt((x * x) / 25 - 1), from: 5, to: 8 },
          { fn: (x) => 3 * Math.sqrt((x * x) / 25 - 1), from: -8, to: -5 },
          { fn: (x) => -3 * Math.sqrt((x * x) / 25 - 1), from: -8, to: -5 },
          { fn: (x) => (3 / 5) * x, from: -8, to: 8, dashed: true },
          { fn: (x) => -(3 / 5) * x, from: -8, to: 8, dashed: true },
        ]}
        points={[{ x: 5, y: 0, filled: false }, { x: -5, y: 0, filled: false }]}
        xMin={-9} xMax={9} yMin={-7} yMax={7}
        xTicks={[{ at: -5, label: "−a" }, { at: 5, label: "a" }]}
        caption="x²/25 − y²/9 = 1 — a = 5, b = 3, c = √34, asymptotes shown dashed"
      />

      <SpeedTricks>
        <Callout type="tip" title="Ellipse: a² = b² + c². Hyperbola: c² = a² + b²">
          In an ellipse, the focus is <em>inside</em> — so c &lt; a. In a hyperbola, the focus is <em>outside</em> — so c &gt; a. That&apos;s why the ± sign flips between the two formulas.
        </Callout>
        <Callout type="tip" title="Identifying the curve from its equation">
          x²/A + y²/B = 1 → ellipse (A, B positive). x²/A − y²/B = 1 → hyperbola. y² = 4ax → parabola. x² + y² = r² → circle.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-hyperbola" title="Examples — Hyperbola">
        <ProblemSolution problemNumber="Example 7">
          <ProblemSolution.Problem>
            <p>Find the foci, vertices, eccentricity, and latus rectum of x²/9 − y²/16 = 1.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a^2 = 9 \to a = 3;\ \ b^2 = 16 \to b = 4`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c^2 = a^2 + b^2 = 9 + 16 = 25 \to c = 5`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(\pm 5, 0)`}</Formula> },
                { label: "Vertices", description: <Formula>{String.raw`(\pm 3, 0)`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{5}{3}`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2(16)}{3} = \frac{32}{3}`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 8">
          <ProblemSolution.Problem>
            <p>Find the equation of the hyperbola with foci (0, ±5) and vertices (0, ±3).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Transverse axis along y-axis", description: <><Formula>{String.raw`\frac{y^2}{a^2} - \frac{x^2}{b^2} = 1`}</Formula> — foci and vertices on the y-axis</> },
                { label: "Identify a, c", description: <Formula>{String.raw`a = 3, c = 5`}</Formula> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = c^2 - a^2 = 25 - 9 = 16`}</Formula> },
                { label: "Equation", description: <Formula>{String.raw`\frac{y^2}{9} - \frac{x^2}{16} = 1`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{y^2}{9} - \frac{x^2}{16} = 1`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <Callout type="warning" title="Hard-Level Tips: Conic Sections Traps">
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Don&apos;t confuse a² and b²:</strong> In ellipse, a is always the semi-major axis (larger). In hyperbola, a² is always the positive term&apos;s denominator. The formula for c changes: ellipse c² = a² − b²; hyperbola c² = a² + b².</li>
          <li><strong>Orientation matters:</strong> Ellipse x²/a² + y²/b² = 1 with a &gt; b has horizontal major axis. Flip the denominators for vertical. Hyperbola: the positive term determines the transverse axis direction.</li>
          <li><strong>Latus Rectum differs:</strong> Ellipse: 2b²/a. Hyperbola: 2b²/a. Same formula — but a and b have different meanings in each context.</li>
          <li><strong>Eccentricity range:</strong> Circle: e = 0. Ellipse: 0 &lt; e &lt; 1. Parabola: e = 1. Hyperbola: e &gt; 1. Memorise this — it&apos;s a frequent MCQ.</li>
          <li><strong>Parabola: which variable is squared?</strong> y² = 4ax → opens along x-axis. x² = 4ay → opens along y-axis. The squared variable tells you the axis of symmetry.</li>
        </ul>
      </Callout>

      <Expandable id="h-misc-ex" title="Miscellaneous Examples">
        <ProblemSolution problemNumber="Misc Ex 1">
          <ProblemSolution.Problem>
            <p>Find the equation of the circle passing through (2, 3) and (−1, 1) with centre on the line y = 2x.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Let centre = (h, 2h)", description: "Centre lies on y = 2x" },
                { label: "Equal radii", description: <Formula>{String.raw`(h-2)^2 + (2h-3)^2 = (h+1)^2 + (2h-1)^2`}</Formula> },
                { label: "Expand", description: <Formula>{String.raw`h^2-4h+4 + 4h^2-12h+9 = h^2+2h+1 + 4h^2-4h+1`}</Formula> },
                { label: "Simplify", description: <Formula>{String.raw`-16h+13 = -2h+2 \to -14h = -11 \to h = \frac{11}{14}`}</Formula> },
                { label: "Centre", description: <Formula>{String.raw`\left(\frac{11}{14}, \frac{22}{14}\right) = \left(\frac{11}{14}, \frac{11}{7}\right)`}</Formula> },
                { label: "Find r²", description: <Formula>{String.raw`r^2 = \left(\frac{11}{14}-2\right)^2 + \left(\frac{11}{7}-3\right)^2 = \left(-\frac{17}{14}\right)^2 + \left(-\frac{10}{7}\right)^2 = \frac{289}{196} + \frac{100}{49} = \frac{289}{196} + \frac{400}{196} = \frac{689}{196}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\left(x - \frac{11}{14}\right)^2 + \left(y - \frac{11}{7}\right)^2 = \frac{689}{196}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Misc Ex 2">
          <ProblemSolution.Problem>
            <p>A rod of length 12 cm moves with its ends always touching the coordinate axes. Find the equation of the locus of a point P on the rod which is 3 cm from the end in contact with the x-axis.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p>Let the ends be A(a, 0) on x-axis and B(0, b) on y-axis with a² + b² = 144.</p>
            <p>P divides AB in ratio 3:9 = 1:3 from A. Using section formula:</p>
            <Stepper
              steps={[
                { label: "Coordinates of P", description: <Formula>{String.raw`P = \left(\frac{3\cdot 0 + 9a}{12}, \frac{3b + 9\cdot 0}{12}\right) = \left(\frac{3a}{4}, \frac{b}{4}\right)`}</Formula> },
                { label: "Set x = 3a/4, y = b/4", description: <Formula>{String.raw`a = \frac{4x}{3},\ \ b = 4y`}</Formula> },
                { label: "Substitute", description: <Formula>{String.raw`\left(\frac{4x}{3}\right)^2 + (4y)^2 = 144 \to \frac{16x^2}{9} + 16y^2 = 144`}</Formula> },
                { label: "Simplify", description: <Formula>{String.raw`\frac{x^2}{9} + y^2 = 9 \to \frac{x^2}{81} + \frac{y^2}{81}\cdot 9 = 1 \to \frac{x^2}{81} + \frac{y^2}{9} = 1`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{81} + \frac{y^2}{9} = 1`} important />
            <p>This is an ellipse with semi-major axis 9 and semi-minor axis 3.</p>
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Misc Ex 3">
          <ProblemSolution.Problem>
            <p>Find the eccentricity of the hyperbola whose latus rectum is 8 and whose conjugate axis is equal to half the distance between its foci.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Given", description: <Formula>{String.raw`\frac{2b^2}{a} = 8 \text{ and } 2b = \frac{1}{2}(2c) \to b = \frac{c}{2}`}</Formula> },
                { label: "From b = c/2", description: <Formula>{String.raw`c = 2b \to c^2 = 4b^2`}</Formula> },
                { label: "Use c² = a² + b²", description: <Formula>{String.raw`4b^2 = a^2 + b^2 \to a^2 = 3b^2 \to a = b\sqrt 3`}</Formula> },
                { label: "From latus rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = 8 \to \frac{2b^2}{b\sqrt 3} = 8 \to \frac{2b}{\sqrt 3} = 8 \to b = 4\sqrt 3`}</Formula> },
                { label: "Find a", description: <Formula>{String.raw`a = 4\sqrt 3 \cdot \sqrt 3 = 12`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c = 2b = 8\sqrt 3`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{8\sqrt 3}{12} = \frac{2\sqrt 3}{3}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`e = \frac{2\sqrt{3}}{3}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <Expandable id="h-ex-10" title="EXERCISE 10.1">
        <ol>
          <li>Find the equation of the circle with centre (0, 2) and radius 2.</li>
          <li>Find the centre and radius of x² + y² + 8x + 10y − 8 = 0.</li>
          <li>Find the equation of the parabola with focus (2, 0) and directrix x = −2.</li>
          <li>Find the focus, axis, and latus rectum of y² = −8x.</li>
          <li>Find the equation of the ellipse with vertices (±5, 0) and foci (±3, 0).</li>
          <li>Find the eccentricity of x²/144 + y²/169 = 1.</li>
          <li>Find the equation of the hyperbola with vertices (±3, 0) and foci (±5, 0).</li>
          <li>Find the latus rectum of x²/25 − y²/16 = 1.</li>
        </ol>
        <Expandable id="h-ex-10-key" title="Answer Key — Exercise 10.1">
          <ol>
            <li>x² + (y − 2)² = 4</li>
            <li>Centre (−4, −5), radius = √(16 + 25 + 8) = √49 = 7</li>
            <li>y² = 8x (a = 2, opens right)</li>
            <li>Focus (−2, 0), axis = x-axis, latus rectum = 8</li>
            <li>x²/25 + y²/16 = 1</li>
            <li>c² = 169 − 144 = 25, c = 5, e = 5/13</li>
            <li>x²/9 − y²/16 = 1</li>
            <li>2b²/a = 2(16)/5 = 32/5</li>
          </ol>
        </Expandable>
      </Expandable>

      <Expandable id="h-ex-10-2" title="EXERCISE 10.2">
        <ol>
          <li>Find the equation of the ellipse with latus rectum 8 and eccentricity 3/5.</li>
          <li>Find the equation of the hyperbola with conjugate axis 5 and eccentricity 4/3.</li>
          <li>A point moves so that its distance from (4, 0) is always half its distance from the line x = 16. Find the locus and identify the conic.</li>
          <li>Find the eccentricity of the ellipse x²/6 + y²/2 = 1.</li>
          <li>Find the equation of the parabola whose vertex is the origin and focus is (0, −6).</li>
        </ol>
        <Expandable id="h-ex-10-2-key" title="Answer Key — Exercise 10.2">
          <ol>
            <li>e = 3/5, 2b²/a = 8. From e = c/a = 3/5, c = 3a/5. b² = a² − c² = a² − 9a²/25 = 16a²/25. So 2(16a²/25)/a = 8 → 32a/25 = 8 → a = 25/4. Then b² = 16(25/4)²/25 = 25. Equation: x²/(625/16) + y²/25 = 1.</li>
            <li>2b = 5 → b = 5/2, e = c/a = 4/3. c² = a² + b² → (4a/3)² = a² + 25/4 → 16a²/9 − a² = 25/4 → 7a²/9 = 25/4 → a² = 225/28. Equation: x²/(225/28) − y²/(25/4) = 1.</li>
            <li>√((x−4)² + y²) = |x−16|/2 → 4((x−4)² + y²) = (x−16)² → 3x² + 4y² = 48 → x²/16 + y²/12 = 1. It&apos;s an <strong>ellipse</strong>.</li>
            <li>a² = 6, b² = 2, c² = 4, c = 2. e = 2/√6 = √6/3.</li>
            <li>x² = −24y (opens downward, a = 6).</li>
          </ol>
        </Expandable>
      </Expandable>

      <Expandable id="h-misc-ex-final" title="Miscellaneous Exercise on Chapter 10">
        <ol>
          <li>Find the equation of the circle with centre (1, −2) and passing through the origin.</li>
          <li>Find the equation of the parabola with latus rectum 10 and focus on the negative x-axis.</li>
          <li>Find the eccentricity of the ellipse whose latus rectum is half the major axis.</li>
          <li>Find the equation of the hyperbola with eccentricity 3/2 and conjugate axis 8.</li>
          <li>Find the centre and radius of 2x² + 2y² + 6x − 4y − 7 = 0.</li>
        </ol>
        <Expandable id="h-misc-ex-final-key" title="Answer Key — Miscellaneous Exercise">
          <ol>
            <li>r² = (1−0)² + (−2−0)² = 5. (x − 1)² + (y + 2)² = 5.</li>
            <li>4a = 10 → a = 5/2. Opens left: y² = −10x.</li>
            <li>LR = 2b²/a = a → b² = a²/2. c² = a² − b² = a²/2. e² = 1/2. e = 1/√2.</li>
            <li>e = 3/2, 2b = 8 → b = 4. c = 3a/2. c² = a² + b² → 9a²/4 = a² + 16 → 5a²/4 = 16 → a² = 64/5. Equation: x²/(64/5) − y²/16 = 1.</li>
            <li>Divide by 2: x² + y² + 3x − 2y − 7/2 = 0. g = 3/2, f = −1, c = −7/2. Centre (−3/2, 1). r² = 9/4 + 1 + 7/2 = 9/4 + 4/4 + 14/4 = 27/4. r = 3√3/2.</li>
          </ol>
        </Expandable>
      </Expandable>
    </>
  );
}
