import { Callout } from "@/components/content/Callout";
import { KeyPoint } from "@/components/content/KeyPoint";
import { Expandable } from "@/components/content/Expandable";
import { Formula, FormulaBlock } from "@/components/content/Formula";
import { ProblemSolution } from "@/components/content/ProblemSolution";
import { Stepper } from "@/components/content/Stepper";
import { FormulaCard } from "@/components/content/FormulaCard";
import { Highlight } from "@/components/content/Highlight";
import { SpeedTricks } from "@/components/content/SpeedTricks";
import { CircleDiagram } from "@/components/content/conic/ConicDiagrams";

export default function ConicSectionsChapter() {
  return (
    <>
      <h2 id="h-cone">10.2 Sections of a Cone</h2>
      <p>
        A <strong>right circular double cone</strong> is generated by rotating a line (generator) about
        a fixed vertical axis. The two nappes meet at the <Highlight>vertex</Highlight>.
      </p>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/d/d3/Conic_sections_with_plane.svg"
          alt="Double cone intersected by a plane producing circle, ellipse, parabola and hyperbola depending on angle beta vs alpha"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs leading-relaxed text-muted-foreground text-center">
          Real figure — double cone cut by a plane at different angles β vs α: <strong>circle</strong> (β=90°), <strong>ellipse</strong> (α&lt;β&lt;90°), <strong>parabola</strong> (β=α), <strong>hyperbola</strong> (β&lt;α). Source:{" "}
          <a href="https://commons.wikimedia.org/wiki/File:Conic_sections_with_plane.svg" target="_blank" rel="noreferrer" className="underline">
            Wikimedia Commons / Pbroks13 (CC0)
          </a>{" "}
          — see NCERT Fig 11.1–11.7. Full PDF:{" "}
          <a href="https://ncert.nic.in/textbook/pdf/kemh111.pdf" target="_blank" rel="noreferrer" className="underline">
            kemh111.pdf
          </a>
          .
        </figcaption>
      </figure>
      <Callout type="important" title="How the Plane Cuts the Cone">
        <table>
          <thead>
            <tr>
              <th>Angle of plane</th>
              <th>Curve obtained</th>
              <th>Condition</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Perpendicular to axis</td>
              <td><strong>Circle</strong></td>
              <td>Plane ⊥ axis</td>
            </tr>
            <tr>
              <td>Tilted, cuts one nappe fully</td>
              <td><strong>Ellipse</strong></td>
              <td>α &lt; β (angle of plane &lt; generator angle)</td>
            </tr>
            <tr>
              <td>Parallel to a generator</td>
              <td><strong>Parabola</strong></td>
              <td>α = β</td>
            </tr>
            <tr>
              <td>Cuts both nappes</td>
              <td><strong>Hyperbola</strong></td>
              <td>α &gt; β</td>
            </tr>
            <tr>
              <td>Through the vertex</td>
              <td><strong>Degenerate cases</strong></td>
              <td>Point, line, or pair of lines</td>
            </tr>
          </tbody>
        </table>
      </Callout>

      <h2 id="h-circle">10.3 Circle</h2>
      <Callout type="important" title="Definition: Circle">
        A <strong>circle</strong> is the set of all points in a plane that are at a fixed distance (the{" "}
        <strong>radius</strong> r) from a fixed point (the <strong>centre</strong> C(h, k)).
      </Callout>
      <CircleDiagram />

      <h3>Equation of a Circle</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Form (Centre-Radius)</p>
        <FormulaBlock latex={String.raw`(x - h)^2 + (y - k)^2 = r^2`} />
        <p className="text-sm text-muted-foreground mt-2">Centre = (h, k), Radius = r</p>
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">Centre at Origin</p>
        <FormulaBlock latex={String.raw`x^2 + y^2 = r^2`} />
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">General Form</p>
        <FormulaBlock latex={String.raw`x^2 + y^2 + 2gx + 2fy + c = 0`} />
        <p className="text-sm text-muted-foreground mt-2">Centre = (−g, −f), Radius = √(g² + f² − c)</p>
      </FormulaCard>
      <KeyPoint>
        The general form expands as (x + g)² + (y + f)² = g² + f² − c. For a valid circle, we need{" "}
        <Highlight>g² + f² − c &gt; 0</Highlight>.
      </KeyPoint>

      <SpeedTricks>
        <Callout type="tip" title="Quick centre from general form">
          Read off g and f from the coefficients of x and y (halve and negate). Centre = (−g, −f). No need to complete the square every time.
        </Callout>
        <Callout type="tip" title="Radius check">
          From general form: r² = g² + f² − c. If this is ≤ 0, the equation has no real circle — a common MCQ trap.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-circle" title="Examples — Circle">
        <ProblemSolution problemNumber="Example 1">
          <ProblemSolution.Problem>
            <p>Find the equation of the circle with centre (3, −2) and radius 4.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <FormulaBlock latex={String.raw`(x - 3)^2 + (y + 2)^2 = 16`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 2">
          <ProblemSolution.Problem>
            <p>Find the centre and radius of x² + y² − 6x + 4y − 12 = 0.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify g, f, c", description: <Formula>{String.raw`2g = -6 \to g = -3;\ \ 2f = 4 \to f = 2;\ \ c = -12`}</Formula> },
                { label: "Centre", description: <Formula>{String.raw`(-g, -f) = (3, -2)`}</Formula> },
                { label: "Radius", description: <Formula>{String.raw`r = \sqrt{9+4+12} = \sqrt{25} = 5`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 3">
          <ProblemSolution.Problem>
            <p>Consider the circle <Formula>{String.raw`C:\ x^2 + y^2 - 4x + 6y - 12 = 0`}</Formula>. Find the centre and radius of <Formula>{String.raw`C`}</Formula>, then find the equation of another circle which is concentric with <Formula>{String.raw`C`}</Formula> and has double the radius.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                {
                  label: "Identify g, f, c",
                  description: <Formula>{String.raw`2g = -4 \implies g = -2;\ \ 2f = 6 \implies f = 3;\ \ c = -12`}</Formula>,
                },
                {
                  label: "Centre",
                  description: <Formula>{String.raw`(-g, -f) = (-(-2), -3) = (2, -3)`}</Formula>,
                },
                {
                  label: "Radius",
                  description: <Formula>{String.raw`r = \sqrt{g^2 + f^2 - c} = \sqrt{4 + 9 + 12} = \sqrt{25} = 5`}</Formula>,
                },
                {
                  label: "Double the radius",
                  description: <Formula>{String.raw`r_{\text{new}} = 5 \times 2 = 10;\ \ \text{Centre stays } (2, -3)`}</Formula>,
                },
                {
                  label: "Standard form",
                  description: <Formula>{String.raw`(x - 2)^2 + (y + 3)^2 = 100`}</Formula>,
                },
                {
                  label: "Expand to general form",
                  description: <Formula>{String.raw`x^2 - 4x + 4 + y^2 + 6y + 9 - 100 = 0 \implies x^2 + y^2 - 4x + 6y - 87 = 0`}</Formula>,
                },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 4">
          <ProblemSolution.Problem>
            <p>Find the equations of the circles with radius 5 whose centres lie on the x-axis and which pass through the point (2, 3).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                {
                  label: "Centre on x-axis",
                  description: <Formula>{String.raw`(h, 0);\ \ r = 5`}</Formula>,
                },
                {
                  label: "Passes through (2, 3)",
                  description: <Formula>{String.raw`(2 - h)^2 + (3 - 0)^2 = 5^2 \implies (2 - h)^2 + 9 = 25`}</Formula>,
                },
                {
                  label: "Solve for h",
                  description: <Formula>{String.raw`(2 - h)^2 = 16 \implies 2 - h = \pm 4`}</Formula>,
                },
                {
                  label: "Case 1: h = 6",
                  description: <Formula>{String.raw`2 - h = -4 \implies h = 6;\ \ x^2 + y^2 - 12x + 11 = 0`}</Formula>,
                },
                {
                  label: "Case 2: h = -2",
                  description: <Formula>{String.raw`2 - h = 4 \implies h = -2;\ \ x^2 + y^2 + 4x - 21 = 0`}</Formula>,
                },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 5">
          <ProblemSolution.Problem>
            <p>Find the centre and radius of the circle <Formula>{String.raw`2x^2 + 2y^2 - x = 0`}</Formula>.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Divide through by 2", description: <Formula>{String.raw`x^2 + y^2 - \frac{x}{2} = 0`}</Formula> },
                { label: "Identify g, f, c", description: <Formula>{String.raw`2g = -\frac{1}{2} \implies g = -\frac{1}{4};\ \ 2f = 0 \implies f = 0;\ \ c = 0`}</Formula> },
                { label: "Centre", description: <Formula>{String.raw`(-g, -f) = \left(-\left(-\frac{1}{4}\right), 0\right) = \left(\frac{1}{4}, 0\right)`}</Formula> },
                { label: "Radius", description: <Formula>{String.raw`r = \sqrt{g^2 + f^2 - c} = \sqrt{\frac{1}{16} + 0 - 0} = \frac{1}{4}`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-parabola">10.4 Parabola</h2>
      <Callout type="important" title="Definition: Parabola">
        A <strong>parabola</strong> is the set of all points in a plane that are equidistant from a fixed
        point (<Highlight>focus</Highlight>) and a fixed line (<Highlight>directrix</Highlight>). i.e. the
        distance from any point on the curve to the focus equals its perpendicular distance to the directrix:{" "}
        <Highlight>PF = PB</Highlight>.
      </Callout>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/parabola-pf-pb-definition.png"
          alt="Parabola definition: PF = PB — distance to focus equals distance to directrix"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          For every point P on the curve, PF = PB (P₁F = P₁B₁, P₂F = P₂B₂, P₃F = P₃B₃) — focus F, directrix l. Source: NCERT Fig 11.13 (textbook screenshot).
        </figcaption>
      </figure>
      <KeyPoint title="Key Terms">
        <ul>
          <li><strong>Focus (S):</strong> the fixed point.</li>
          <li><strong>Directrix:</strong> the fixed line.</li>
          <li><strong>Vertex:</strong> midpoint of the perpendicular from focus to directrix.</li>
          <li><strong>Axis:</strong> the line through the focus perpendicular to the directrix.</li>
          <li><strong>Latus Rectum:</strong> the chord through the focus perpendicular to the axis. Length ={" "}
            <Highlight>4a</Highlight>.</li>
        </ul>
      </KeyPoint>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/parabola-components.png"
          alt="Parabola components: vertex, focus, axis of symmetry, directrix"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Core components of a standard parabola — vertex, focus, axis of symmetry, and directrix. Source: NCERT Fig 11.14 (textbook screenshot).
        </figcaption>
      </figure>

      <h3>Standard Equations of Parabola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Four Standard Forms</p>
        <table>
          <thead>
            <tr>
              <th>Parabola</th>
              <th>Equation</th>
              <th>Axis</th>
              <th>Vertex</th>
              <th>Focus</th>
              <th>Directrix</th>
              <th>Latus Rectum</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Right Hand</td>
              <td>y² = 4ax</td>
              <td>X-axis</td>
              <td>(0, 0)</td>
              <td>(a, 0)</td>
              <td>x = −a</td>
              <td>4a</td>
            </tr>
            <tr>
              <td>Left Hand</td>
              <td>y² = −4ax</td>
              <td>X-axis</td>
              <td>(0, 0)</td>
              <td>(−a, 0)</td>
              <td>x = a</td>
              <td>4a</td>
            </tr>
            <tr>
              <td>Upward</td>
              <td>x² = 4ay</td>
              <td>Y-axis</td>
              <td>(0, 0)</td>
              <td>(0, a)</td>
              <td>y = −a</td>
              <td>4a</td>
            </tr>
            <tr>
              <td>Downward</td>
              <td>x² = −4ay</td>
              <td>Y-axis</td>
              <td>(0, 0)</td>
              <td>(0, −a)</td>
              <td>y = a</td>
              <td>4a</td>
            </tr>
          </tbody>
        </table>
        <p className="text-sm text-muted-foreground mt-2">Here a is the distance from the vertex to the focus (and from the vertex to the directrix).</p>
      </FormulaCard>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/parabola-horizontal-forms.png"
          alt="Horizontal parabolas: y²=4ax (right) and y²=−4ax (left)"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Horizontal parabolas along the x-axis — right-opening y² = 4ax and left-opening y² = −4ax. Source: NCERT Fig 11.15 (textbook screenshot).
        </figcaption>
      </figure>
      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/parabola-vertical-forms.png"
          alt="Vertical parabolas: x²=4ay (up) and x²=−4ay (down)"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Vertical parabolas along the y-axis — upward-opening x² = 4ay and downward-opening x² = −4ay. Source: NCERT Fig 11.15 (textbook screenshot).
        </figcaption>
      </figure>

      <SpeedTricks>
        <Callout type="tip" title="Remember the four forms">
          y² = ±4ax opens horizontally (± gives left/right). x² = ±4ay opens vertically (± gives up/down). The variable that is <em>squared</em> determines the direction.
        </Callout>
        <Callout type="tip" title="Latus Rectum = 4a always">
          For all four standard parabolas, the latus rectum length is 4a. Just read a from the equation — no memorising separate formulas.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-parabola" title="Examples — Parabola">
        <ProblemSolution problemNumber="Example 3">
          <ProblemSolution.Problem>
            <p>Find the focus, directrix, and latus rectum of y² = 12x.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Compare with y² = 4ax", description: <Formula>{String.raw`4a = 12 \to a = 3`}</Formula> },
                { label: "Focus", description: "(a, 0) = (3, 0)" },
                { label: "Directrix", description: "x = −a = −3" },
                { label: "Latus Rectum", description: "4a = 12" },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 4">
          <ProblemSolution.Problem>
            <p>Find the equation of the parabola with focus (0, 4) and directrix y = −4.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p>Focus is above the directrix on the y-axis, so the parabola opens upward.</p>
            <Stepper
              steps={[
                { label: "Identify a", description: "Distance from vertex (0,0) to focus = a = 4" },
                { label: "Form", description: <Formula>{String.raw`x^2 = 4ay = 4(4)y = 16y`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`x^2 = 16y`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 5">
          <ProblemSolution.Problem>
            <p>For the parabola <Formula>{String.raw`x^2 = -8y`}</Formula>, find (i) the coordinates of the focus, and (ii) the axis, equation of the directrix, and length of the latus rectum.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p className="mb-2"><strong>Part (i) — Focus</strong></p>
            <Stepper
              steps={[
                { label: "Compare with x² = −4ay", description: <Formula>{String.raw`-4a = -8 \implies a = 2`}</Formula> },
                { label: "Focus", description: <Formula>{String.raw`(0, -a) = (0, -2)`}</Formula> },
              ]}
            />
            <p className="mt-3 mb-2"><strong>Part (ii) — Axis, Directrix, Latus Rectum</strong></p>
            <ul className="list-disc pl-5 space-y-1 text-sm">
              <li><strong>Axis:</strong> Y-axis.</li>
              <li><strong>Directrix:</strong> <Formula>{String.raw`y = a \implies y = 2`}</Formula>.</li>
              <li><strong>Latus Rectum:</strong> <Formula>{String.raw`4a = 4 \times 2 = 8`}</Formula>.</li>
            </ul>
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 6">
          <ProblemSolution.Problem>
            <p>Find the equation of the parabola with focus (6, 0) and directrix x = −6.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Read a", description: <Formula>{String.raw`(a, 0) = (6, 0) \implies a = 6`}</Formula> },
                { label: "Check directrix", description: <Formula>{String.raw`x = -a = -6`}</Formula> },
                { label: "Form (opens right)", description: <Formula>{String.raw`y^2 = 4ax`}</Formula> },
                { label: "Substitute", description: <Formula>{String.raw`y^2 = 4 \times 6 \times x = 24x`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`y^2 = 24x`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 7">
          <ProblemSolution.Problem>
            <p>Which of the following equations represents a parabola that is symmetrical about the positive y-axis?</p>
            <ol className="list-decimal pl-5 space-y-1 text-sm">
              <li>y² = 8x</li>
              <li>y² = −8x</li>
              <li>x² + 4y = 0</li>
              <li>x² − 4y = 0</li>
            </ol>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p>A parabola symmetrical about the positive y-axis has the form <Formula>{String.raw`x^2 = 4ay`}</Formula>.</p>
            <Stepper
              steps={[
                { label: "Eliminate (i), (ii)", description: "y² = ±8x open along the x-axis — not symmetric about the y-axis." },
                { label: "Rearrange (iii)", description: <Formula>{String.raw`x^2 + 4y = 0 \implies x^2 = -4y`}</Formula> },
                { label: "Rearrange (iv)", description: <Formula>{String.raw`x^2 - 4y = 0 \implies x^2 = 4y`}</Formula> },
                { label: "Conclusion", description: "(iv) matches x² = 4ay — symmetric about the positive y-axis." },
              ]}
            />
            <FormulaBlock latex={String.raw`\text{Correct option: (iv)}\ x^2 - 4y = 0`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-ellipse">10.5 Ellipse</h2>
      <Callout type="important" title="Definition: Ellipse">
        An <strong>ellipse</strong> is the set of all points in a plane such that the{" "}
        <Highlight>sum of distances from two fixed points (foci)</Highlight> is a constant.
      </Callout>

      <h3>Standard Equations of Ellipse</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Forms</p>
        <table>
          <thead>
            <tr>
              <th>Property</th>
              <th>Major Axis along X-axis</th>
              <th>Major Axis along Y-axis</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Standard Form</strong></td>
              <td>x²/a² + y²/b² = 1 &nbsp;(a &gt; b)</td>
              <td>x²/b² + y²/a² = 1 &nbsp;(a &gt; b)</td>
            </tr>
            <tr>
              <td><strong>Centre</strong></td>
              <td>(0, 0)</td>
              <td>(0, 0)</td>
            </tr>
            <tr>
              <td><strong>Foci</strong></td>
              <td>(±c, 0)</td>
              <td>(0, ±c)</td>
            </tr>
            <tr>
              <td><strong>Vertices</strong></td>
              <td>(±a, 0)</td>
              <td>(0, ±a)</td>
            </tr>
            <tr>
              <td><strong>Major Axis Length</strong></td>
              <td>2a</td>
              <td>2a</td>
            </tr>
            <tr>
              <td><strong>Minor Axis Length</strong></td>
              <td>2b</td>
              <td>2b</td>
            </tr>
            <tr>
              <td><strong>Latus Rectum</strong></td>
              <td>2b²/a</td>
              <td>2b²/a</td>
            </tr>
            <tr>
              <td><strong>Eccentricity</strong></td>
              <td>e = c/a</td>
              <td>e = c/a</td>
            </tr>
          </tbody>
        </table>
      </FormulaCard>

      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/ellipse-foci-vertices.png"
          alt="Ellipse with foci and vertices"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Ellipse with its foci S, S′ and vertices — PS + PS′ = 2a. Source: NCERT Fig 11.25 (textbook screenshot).
        </figcaption>
      </figure>

      <FormulaCard>
        <p className="font-semibold mb-2">Key Relations</p>
        <FormulaBlock latex={String.raw`c^2 = a^2 - b^2 \implies c = \sqrt{a^2 - b^2}`} />
        <FormulaBlock latex={String.raw`e = \frac{c}{a}, \quad 0 < e < 1`} />
        <FormulaBlock latex={String.raw`\text{Latus Rectum} = \frac{2b^2}{a}`} />
        <FormulaBlock latex={String.raw`PS + PS' = 2a \quad \text{(focal distance property for any point } P \text{)}`} />
        <p className="text-sm text-muted-foreground mt-2">a = semi-major axis, b = semi-minor axis, c = distance from centre to focus, e = eccentricity</p>
      </FormulaCard>

      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/ellipse-latus-rectum.png"
          alt="Ellipse latus rectum"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Latus rectum of an ellipse — chord through a focus perpendicular to the major axis, length 2b²/a. Source: NCERT Fig 11.27 (textbook screenshot).
        </figcaption>
      </figure>

      <KeyPoint title="Properties of Ellipse">
        <ul>
          <li><strong>Eccentricity:</strong> 0 &lt; e &lt; 1 (e = 0 gives a circle).</li>
          <li><strong>Vertices:</strong> endpoints of the major axis — (±a, 0) or (0, ±a).</li>
          <li><strong>Major axis length:</strong> 2a. <strong>Minor axis length:</strong> 2b.</li>
          <li><strong>Latus Rectum:</strong> chord through a focus perpendicular to the major axis. Length = 2b²/a.</li>
          <li><Highlight>a² = b² + c²</Highlight> — the larger of a² and b² equals the sum of the other two.</li>
        </ul>
      </KeyPoint>

      <SpeedTricks>
        <Callout type="tip" title="Which is a, which is b?">
          Always: a &gt; b. If the larger denominator is under x², major axis is horizontal. If under y², vertical. Don&apos;t assume a is always under x².
        </Callout>
        <Callout type="tip" title="a² = b² + c² (not c² = a² + b²)">
          Common exam trap: for ellipse, c² = a² − b² (so a² = b² + c²). For hyperbola, c² = a² + b². The roles of a and c are different.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-ellipse" title="Examples — Ellipse">
        <ProblemSolution problemNumber="Example 5">
          <ProblemSolution.Problem>
            <p>Find the equation of the ellipse with foci (±3, 0) and vertices (±5, 0).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a and c", description: <Formula>{String.raw`a = 5, c = 3`}</Formula> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = a^2 - c^2 = 25 - 9 = 16 \to b = 4`}</Formula> },
                { label: "Equation", description: <><Formula>{String.raw`\frac{x^2}{25} + \frac{y^2}{16} = 1`}</Formula> — major axis along the x-axis</> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{25} + \frac{y^2}{16} = 1`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 6">
          <ProblemSolution.Problem>
            <p>Find the eccentricity, foci, and latus rectum of x²/16 + y²/9 = 1.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a^2 = 16 \to a = 4;\ \ b^2 = 9 \to b = 3`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c^2 = 16 - 9 = 7 \to c = \sqrt 7`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{\sqrt 7}{4}`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(\pm\sqrt 7, 0)`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2(9)}{4} = \frac{9}{2}`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 7">
          <ProblemSolution.Problem>
            <p>Find the coordinates of the foci, vertices, length of the major axis, and length of the latus rectum of x²/36 + y²/16 = 1.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a^2 = 36 \to a = 6;\ \ b^2 = 16 \to b = 4`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c = \sqrt{36 - 16} = \sqrt{20} = 2\sqrt{5}`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(\pm 2\sqrt{5}, 0)`}</Formula> },
                { label: "Vertices", description: <Formula>{String.raw`(\pm 6, 0)`}</Formula> },
                { label: "Major axis", description: <Formula>{String.raw`2a = 12`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2 \times 16}{6} = \frac{16}{3}`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 8">
          <ProblemSolution.Problem>
            <p>Find the foci, vertices, eccentricity, and latus rectum of 100x² + 25y² = 2500.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Normalise", description: <><Formula>{String.raw`\frac{x^2}{25} + \frac{y^2}{100} = 1`}</Formula> — divide by 2500</> },
                { label: "Identify a, b", description: <><Formula>{String.raw`a^2 = 100 \to a = 10;\ \ b^2 = 25 \to b = 5`}</Formula> — major axis along the y-axis</> },
                { label: "Find c", description: <Formula>{String.raw`c = \sqrt{100 - 25} = \sqrt{75} = 5\sqrt{3}`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(0, \pm 5\sqrt{3})`}</Formula> },
                { label: "Vertices", description: <Formula>{String.raw`(0, \pm 10)`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{5\sqrt{3}}{10} = \frac{\sqrt{3}}{2}`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2 \times 25}{10} = 5`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 9">
          <ProblemSolution.Problem>
            <p>An ellipse has vertices (±5, 0) and foci (±4, 0). Find its equation and eccentricity.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, c", description: <Formula>{String.raw`a = 5, c = 4`}</Formula> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = a^2 - c^2 = 25 - 16 = 9`}</Formula> },
                { label: "Equation", description: <Formula>{String.raw`\frac{x^2}{25} + \frac{y^2}{9} = 1`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{4}{5}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{25} + \frac{y^2}{9} = 1, \quad e = \frac{4}{5}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 10">
          <ProblemSolution.Problem>
            <p>For the ellipse x²/25 + y²/9 = 1, let A and B be the foci and C a point on the ellipse with BC ⊥ AB. Find the side lengths of triangle ABC.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a = 5, b = 3`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c = \sqrt{25 - 9} = 4`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`A = (-4, 0),\ B = (4, 0)`}</Formula> },
                { label: "AB", description: <Formula>{String.raw`2c = 8`}</Formula> },
                { label: "BC", description: <><Formula>{String.raw`\frac{b^2}{a} = \frac{9}{5} = 1.8`}</Formula> — semi-latus rectum</> },
                { label: "AC", description: <><Formula>{String.raw`AC + BC = 2a \implies AC = 10 - 1.8 = 8.2`}</Formula> — focal distance property</> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 11">
          <ProblemSolution.Problem>
            <p>Let S and S′ be the foci of x²/25 + y²/16 = 1, and P any point on the ellipse. Find PS + PS′.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a", description: <Formula>{String.raw`a^2 = 25 \to a = 5`}</Formula> },
                { label: "Focal distance property", description: <Formula>{String.raw`PS + PS' = 2a = 10`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`PS + PS' = 10`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 12">
          <ProblemSolution.Problem>
            <p>An ellipse passes through (3, 1) and has foci (±4, 0). Find the length of the major axis, its standard equation, eccentricity, and latus rectum.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Foci", description: <Formula>{String.raw`S(-4, 0),\ S'(4, 0),\ P(3, 1)`}</Formula> },
                { label: "PS", description: <Formula>{String.raw`\sqrt{(3+4)^2 + 1^2} = \sqrt{50} = 5\sqrt{2}`}</Formula> },
                { label: "PS′", description: <Formula>{String.raw`\sqrt{(3-4)^2 + 1^2} = \sqrt{2}`}</Formula> },
                { label: "2a", description: <Formula>{String.raw`PS + PS' = 6\sqrt{2} \quad (\text{major axis length})`}</Formula> },
                { label: "a²", description: <Formula>{String.raw`a = 3\sqrt{2} \to a^2 = 18`}</Formula> },
                { label: "b²", description: <Formula>{String.raw`b^2 = a^2 - c^2 = 18 - 16 = 2`}</Formula> },
                { label: "Equation", description: <Formula>{String.raw`\frac{x^2}{18} + \frac{y^2}{2} = 1`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{4}{3\sqrt{2}}`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{4}{3\sqrt{2}}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{18} + \frac{y^2}{2} = 1, \quad 2a = 6\sqrt{2}, \quad e = \frac{4}{3\sqrt{2}}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 13">
          <ProblemSolution.Problem>
            <p>Find the equation of the ellipse with centre at the origin, major axis along the x-axis, passing through (4, 3) and (−1, 4).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Standard form", description: <><Formula>{String.raw`\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1`}</Formula> — centre at origin, major axis along x-axis, a² &gt; b²</> },
                { label: "Substitute (4, 3)", description: <><Formula>{String.raw`\frac{16}{a^2} + \frac{9}{b^2} = 1`}</Formula> (equation 1)</> },
                { label: "Substitute (−1, 4)", description: <><Formula>{String.raw`\frac{1}{a^2} + \frac{16}{b^2} = 1`}</Formula> (equation 2)</> },
                { label: "Eliminate a²", description: <><Formula>{String.raw`16 \times (2) - (1)`}</Formula> — multiply eq (2) by 16 and subtract eq (1)</> },
                { label: "Solve for b²", description: <Formula>{String.raw`\frac{256}{b^2} - \frac{9}{b^2} = 15 \implies \frac{247}{b^2} = 15 \implies b^2 = \frac{247}{15}`}</Formula> },
                { label: "Solve for a²", description: <><Formula>{String.raw`\frac{1}{a^2} = 1 - \frac{16 \times 15}{247} = \frac{7}{247} \implies a^2 = \frac{247}{7}`}</Formula> (using equation 2)</> },
                { label: "Equation", description: <Formula>{String.raw`\frac{7x^2}{247} + \frac{15y^2}{247} = 1 \implies 7x^2 + 15y^2 = 247`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`7x^2 + 15y^2 = 247, \quad a^2 = \frac{247}{7} > b^2 = \frac{247}{15}`} important />
            <p className="text-sm text-muted-foreground mt-2">Since a² &gt; b², the major axis is along the x-axis as required.</p>
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <h2 id="h-hyperbola">10.6 Hyperbola</h2>
      <Callout type="important" title="Definition: Hyperbola">
        A <strong>hyperbola</strong> is the set of all points in a plane such that the{" "}
        <Highlight>difference of distances from two fixed points (foci)</Highlight> is a constant.
      </Callout>

      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/hyperbola-definition.png"
          alt="Hyperbola definition with foci"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Hyperbola with its foci S, S′ — |PS′ − PS| = 2a. Source: NCERT (textbook screenshot).
        </figcaption>
      </figure>

      <figure className="my-6 rounded-xl border border-border/40 overflow-hidden bg-card">
        <img
          src="/images/maths/conic-sections/hyperbola-components.png"
          alt="Hyperbola foci, vertices and axes"
          className="w-full h-auto"
          loading="lazy"
        />
        <figcaption className="px-4 py-2.5 bg-muted/20 border-t border-border/30 text-xs text-muted-foreground text-center leading-relaxed">
          Hyperbola components — foci, vertices, transverse/conjugate axes. Source: NCERT (textbook screenshot).
        </figcaption>
      </figure>

      <h3>Standard Equation of Hyperbola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Standard Forms</p>
        <table>
          <thead>
            <tr>
              <th>Property</th>
              <th>Transverse Axis along X-axis</th>
              <th>Transverse Axis along Y-axis</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Standard Form</strong></td>
              <td>x²/a² − y²/b² = 1</td>
              <td>y²/a² − x²/b² = 1</td>
            </tr>
            <tr>
              <td><strong>Centre</strong></td>
              <td>(0, 0)</td>
              <td>(0, 0)</td>
            </tr>
            <tr>
              <td><strong>Foci</strong></td>
              <td>(±c, 0)</td>
              <td>(0, ±c)</td>
            </tr>
            <tr>
              <td><strong>Vertices</strong></td>
              <td>(±a, 0)</td>
              <td>(0, ±a)</td>
            </tr>
            <tr>
              <td><strong>Transverse Axis</strong></td>
              <td>2a</td>
              <td>2a</td>
            </tr>
            <tr>
              <td><strong>Conjugate Axis</strong></td>
              <td>2b</td>
              <td>2b</td>
            </tr>
            <tr>
              <td><strong>Latus Rectum</strong></td>
              <td>2b²/a</td>
              <td>2b²/a</td>
            </tr>
          </tbody>
        </table>
      </FormulaCard>

      <FormulaCard>
        <p className="font-semibold mb-2">Key Relations</p>
        <FormulaBlock latex={String.raw`c^2 = a^2 + b^2 \implies c = \sqrt{a^2 + b^2}`} />
        <FormulaBlock latex={String.raw`e = \frac{c}{a} > 1`} />
        <FormulaBlock latex={String.raw`\text{Latus Rectum} = \frac{2b^2}{a}`} />
        <FormulaBlock latex={String.raw`|PS' - PS| = 2a \quad \text{(focal difference property for any point } P \text{)}`} />
        <p className="text-sm text-muted-foreground mt-2">
          Eccentricity comparison: circle e = 0, ellipse 0 &lt; e &lt; 1, parabola e = 1, hyperbola e &gt; 1.
        </p>
      </FormulaCard>

      <KeyPoint title="Properties of Hyperbola">
        <ul>
          <li><strong>Transverse axis:</strong> the axis passing through the foci. Length = 2a.</li>
          <li><strong>Conjugate axis:</strong> perpendicular to transverse axis through the centre. Length = 2b.</li>
          <li><strong>Vertices:</strong> (±a, 0) — endpoints of the transverse axis.</li>
          <li><strong>Foci:</strong> (±c, 0) where c² = a² + b².</li>
          <li><strong>Eccentricity:</strong> e = c/a &gt; 1 (always greater than 1 for hyperbola).</li>
          <li><strong>Asymptotes:</strong> y = ±(b/a)x — the hyperbola approaches these lines at infinity.</li>
        </ul>
      </KeyPoint>

      <h3>Equilateral Hyperbola</h3>
      <FormulaCard>
        <p className="font-semibold mb-2">Equilateral (Rectangular) Hyperbola</p>
        <FormulaBlock latex={String.raw`x^2 - y^2 = a^2 \quad \text{(when } a = b\text{)}`} />
        <p className="text-sm text-muted-foreground mt-2">Eccentricity = √2. Asymptotes are perpendicular (y = ±x).</p>
      </FormulaCard>

      <SpeedTricks>
        <Callout type="tip" title="Ellipse: a² = b² + c². Hyperbola: c² = a² + b²">
          In an ellipse, the focus is <em>inside</em> — so c &lt; a. In a hyperbola, the focus is <em>outside</em> — so c &gt; a. That&apos;s why the ± sign flips between the two formulas.
        </Callout>
        <Callout type="tip" title="Identifying the curve from its equation">
          x²/A + y²/B = 1 → ellipse (A, B positive). x²/A − y²/B = 1 → hyperbola. y² = 4ax → parabola. x² + y² = r² → circle.
        </Callout>
      </SpeedTricks>

      <Expandable id="h-ex-hyperbola" title="Examples — Hyperbola">
        <ProblemSolution problemNumber="Example 7">
          <ProblemSolution.Problem>
            <p>For the hyperbola x²/9 − y²/16 = 1, find the foci, vertices, eccentricity, latus rectum, and the lengths of the transverse and conjugate axes.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Identify a, b", description: <Formula>{String.raw`a^2 = 9 \to a = 3;\ \ b^2 = 16 \to b = 4`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c^2 = a^2 + b^2 = 9 + 16 = 25 \to c = 5`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(\pm 5, 0)`}</Formula> },
                { label: "Vertices", description: <Formula>{String.raw`(\pm 3, 0)`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{5}{3}`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2(16)}{3} = \frac{32}{3}`}</Formula> },
                { label: "Axes", description: <><Formula>{String.raw`2a = 6,\quad 2b = 8`}</Formula> — transverse and conjugate axes</> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 8">
          <ProblemSolution.Problem>
            <p>Find the equation of the hyperbola with foci (0, ±5) and vertices (0, ±3).</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Transverse axis along y-axis", description: <><Formula>{String.raw`\frac{y^2}{a^2} - \frac{x^2}{b^2} = 1`}</Formula> — foci and vertices on the y-axis</> },
                { label: "Identify a, c", description: <Formula>{String.raw`a = 3, c = 5`}</Formula> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = c^2 - a^2 = 25 - 9 = 16`}</Formula> },
                { label: "Equation", description: <Formula>{String.raw`\frac{y^2}{9} - \frac{x^2}{16} = 1`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{y^2}{9} - \frac{x^2}{16} = 1`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 9">
          <ProblemSolution.Problem>
            <p>Find the equation of the hyperbola whose foci are (0, ±8) and the length of whose latus rectum is 24.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Foci", description: <><Formula>{String.raw`c = 8 \implies c^2 = 64`}</Formula> — foci (0, ±c), so transverse axis along the y-axis</> },
                { label: "Latus rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = 24 \implies b^2 = 12a`}</Formula> },
                { label: "Use c² = a² + b²", description: <Formula>{String.raw`64 = a^2 + 12a \implies a^2 + 12a - 64 = 0`}</Formula> },
                { label: "Solve quadratic", description: <Formula>{String.raw`(a+6)^2 = 100 \implies a + 6 = \pm 10`}</Formula> },
                { label: "Choose a", description: <>{<Formula>{String.raw`a = 4`}</Formula>} (a = −16 rejected as a &gt; 0)</> },
                { label: "Find b²", description: <Formula>{String.raw`b^2 = 12a = 12 \times 4 = 48`}</Formula> },
                { label: "Equation", description: <><Formula>{String.raw`\frac{y^2}{16} - \frac{x^2}{48} = 1`}</Formula> — transverse axis along the y-axis</> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{y^2}{16} - \frac{x^2}{48} = 1`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 10">
          <ProblemSolution.Problem>
            <p>For the conic 9y² − 4x² = 36, find the foci, eccentricity, and length of the latus rectum.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Normalise", description: <><Formula>{String.raw`\frac{y^2}{4} - \frac{x^2}{9} = 1`}</Formula> — divide by 36</> },
                { label: "Identify a, b", description: <>{<Formula>{String.raw`a^2 = 4 \to a = 2;\ \ b^2 = 9 \to b = 3`}</Formula>} — transverse axis along the y-axis</> },
                { label: "Find c", description: <Formula>{String.raw`c = \sqrt{4 + 9} = \sqrt{13}`}</Formula> },
                { label: "Foci", description: <Formula>{String.raw`(0, \pm \sqrt{13})`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{\sqrt{13}}{2}`}</Formula> },
                { label: "Latus Rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = \frac{2 \times 9}{2} = 9`}</Formula> },
              ]}
            />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Example 11">
          <ProblemSolution.Problem>
            <p>A hyperbola with its transverse axis along the x-axis, centre at the origin, and foci (±√10, 0) passes through (3, 2). Find its equation.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Foci", description: <>{<Formula>{String.raw`c = \sqrt{10} \implies a^2 + b^2 = 10`}</Formula>} (equation 1)</> },
                { label: "Point (3, 2)", description: <>{<Formula>{String.raw`\frac{9}{a^2} - \frac{4}{b^2} = 1`}</Formula>} (equation 2)</> },
                { label: "Substitute b² = 10 − a²", description: <Formula>{String.raw`\frac{9}{a^2} - \frac{4}{10-a^2} = 1`}</Formula> },
                { label: "Multiply through", description: <Formula>{String.raw`9(10-a^2) - 4a^2 = a^2(10-a^2) \implies a^4 - 23a^2 + 90 = 0`}</Formula> },
                { label: "Factor", description: <Formula>{String.raw`(a^2 - 5)(a^2 - 18) = 0 \implies a^2 = 5 \ \text{or}\ 18`}</Formula> },
                { label: "Reject a² = 18", description: <><Formula>{String.raw`a^2 + b^2 = 10 \implies a^2 < 10`}</Formula> — reject 18</> },
                { label: "b²", description: <Formula>{String.raw`b^2 = 10 - 5 = 5`}</Formula> },
                { label: "Equation", description: <Formula>{String.raw`\frac{x^2}{5} - \frac{y^2}{5} = 1 \implies x^2 - y^2 = 5`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`x^2 - y^2 = 5`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <Callout type="warning" title="Hard-Level Tips: Conic Sections Traps">
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Don&apos;t confuse a² and b²:</strong> In ellipse, a is always the semi-major axis (larger). In hyperbola, a² is always the positive term&apos;s denominator. The formula for c changes: ellipse c² = a² − b²; hyperbola c² = a² + b².</li>
          <li><strong>Orientation matters:</strong> Ellipse x²/a² + y²/b² = 1 with a &gt; b has horizontal major axis. Flip the denominators for vertical. Hyperbola: the positive term determines the transverse axis direction.</li>
          <li><strong>Latus Rectum differs:</strong> Ellipse: 2b²/a. Hyperbola: 2b²/a. Same formula — but a and b have different meanings in each context.</li>
          <li><strong>Eccentricity range:</strong> Circle: e = 0. Ellipse: 0 &lt; e &lt; 1. Parabola: e = 1. Hyperbola: e &gt; 1. Memorise this — it&apos;s a frequent MCQ.</li>
          <li><strong>Parabola: which variable is squared?</strong> y² = 4ax → opens along x-axis. x² = 4ay → opens along y-axis. The squared variable tells you the axis of symmetry.</li>
        </ul>
      </Callout>

      <Expandable id="h-misc-ex" title="Miscellaneous Examples">
        <ProblemSolution problemNumber="Misc Ex 1">
          <ProblemSolution.Problem>
            <p>Find the equation of the circle passing through (2, 3) and (−1, 1) with centre on the line y = 2x.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Let centre = (h, 2h)", description: "Centre lies on y = 2x" },
                { label: "Equal radii", description: <Formula>{String.raw`(h-2)^2 + (2h-3)^2 = (h+1)^2 + (2h-1)^2`}</Formula> },
                { label: "Expand", description: <Formula>{String.raw`h^2-4h+4 + 4h^2-12h+9 = h^2+2h+1 + 4h^2-4h+1`}</Formula> },
                { label: "Simplify", description: <Formula>{String.raw`-16h+13 = -2h+2 \to -14h = -11 \to h = \frac{11}{14}`}</Formula> },
                { label: "Centre", description: <Formula>{String.raw`\left(\frac{11}{14}, \frac{22}{14}\right) = \left(\frac{11}{14}, \frac{11}{7}\right)`}</Formula> },
                { label: "Find r²", description: <Formula>{String.raw`r^2 = \left(\frac{11}{14}-2\right)^2 + \left(\frac{11}{7}-3\right)^2 = \left(-\frac{17}{14}\right)^2 + \left(-\frac{10}{7}\right)^2 = \frac{289}{196} + \frac{100}{49} = \frac{289}{196} + \frac{400}{196} = \frac{689}{196}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\left(x - \frac{11}{14}\right)^2 + \left(y - \frac{11}{7}\right)^2 = \frac{689}{196}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Misc Ex 2">
          <ProblemSolution.Problem>
            <p>A rod of length 12 cm moves with its ends always touching the coordinate axes. Find the equation of the locus of a point P on the rod which is 3 cm from the end in contact with the x-axis.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <p>Let the ends be A(a, 0) on x-axis and B(0, b) on y-axis with a² + b² = 144.</p>
            <p>P divides AB in ratio 3:9 = 1:3 from A. Using section formula:</p>
            <Stepper
              steps={[
                { label: "Coordinates of P", description: <Formula>{String.raw`P = \left(\frac{3\cdot 0 + 9a}{12}, \frac{3b + 9\cdot 0}{12}\right) = \left(\frac{3a}{4}, \frac{b}{4}\right)`}</Formula> },
                { label: "Set x = 3a/4, y = b/4", description: <Formula>{String.raw`a = \frac{4x}{3},\ \ b = 4y`}</Formula> },
                { label: "Substitute", description: <Formula>{String.raw`\left(\frac{4x}{3}\right)^2 + (4y)^2 = 144 \to \frac{16x^2}{9} + 16y^2 = 144`}</Formula> },
                { label: "Simplify", description: <Formula>{String.raw`\frac{x^2}{9} + y^2 = 9 \to \frac{x^2}{81} + \frac{y^2}{81}\cdot 9 = 1 \to \frac{x^2}{81} + \frac{y^2}{9} = 1`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`\frac{x^2}{81} + \frac{y^2}{9} = 1`} important />
            <p>This is an ellipse with semi-major axis 9 and semi-minor axis 3.</p>
          </ProblemSolution.Solution>
        </ProblemSolution>

        <ProblemSolution problemNumber="Misc Ex 3">
          <ProblemSolution.Problem>
            <p>Find the eccentricity of the hyperbola whose latus rectum is 8 and whose conjugate axis is equal to half the distance between its foci.</p>
          </ProblemSolution.Problem>
          <ProblemSolution.Solution>
            <Stepper
              steps={[
                { label: "Given", description: <Formula>{String.raw`\frac{2b^2}{a} = 8 \text{ and } 2b = \frac{1}{2}(2c) \to b = \frac{c}{2}`}</Formula> },
                { label: "From b = c/2", description: <Formula>{String.raw`c = 2b \to c^2 = 4b^2`}</Formula> },
                { label: "Use c² = a² + b²", description: <Formula>{String.raw`4b^2 = a^2 + b^2 \to a^2 = 3b^2 \to a = b\sqrt 3`}</Formula> },
                { label: "From latus rectum", description: <Formula>{String.raw`\frac{2b^2}{a} = 8 \to \frac{2b^2}{b\sqrt 3} = 8 \to \frac{2b}{\sqrt 3} = 8 \to b = 4\sqrt 3`}</Formula> },
                { label: "Find a", description: <Formula>{String.raw`a = 4\sqrt 3 \cdot \sqrt 3 = 12`}</Formula> },
                { label: "Find c", description: <Formula>{String.raw`c = 2b = 8\sqrt 3`}</Formula> },
                { label: "Eccentricity", description: <Formula>{String.raw`e = \frac{c}{a} = \frac{8\sqrt 3}{12} = \frac{2\sqrt 3}{3}`}</Formula> },
              ]}
            />
            <FormulaBlock latex={String.raw`e = \frac{2\sqrt{3}}{3}`} important />
          </ProblemSolution.Solution>
        </ProblemSolution>
      </Expandable>

      <Expandable id="h-ex-10" title="EXERCISE 10.1">
        <ol>
          <li>Find the equation of the circle with centre (0, 2) and radius 2.</li>
          <li>Find the centre and radius of x² + y² + 8x + 10y − 8 = 0.</li>
          <li>Find the equation of the parabola with focus (2, 0) and directrix x = −2.</li>
          <li>Find the focus, axis, and latus rectum of y² = −8x.</li>
          <li>Find the equation of the ellipse with vertices (±5, 0) and foci (±3, 0).</li>
          <li>Find the eccentricity of x²/144 + y²/169 = 1.</li>
          <li>Find the equation of the hyperbola with vertices (±3, 0) and foci (±5, 0).</li>
          <li>Find the latus rectum of x²/25 − y²/16 = 1.</li>
        </ol>
        <Expandable id="h-ex-10-key" title="Answer Key — Exercise 10.1">
          <ol>
            <li>x² + (y − 2)² = 4</li>
            <li>Centre (−4, −5), radius = √(16 + 25 + 8) = √49 = 7</li>
            <li>y² = 8x (a = 2, opens right)</li>
            <li>Focus (−2, 0), axis = x-axis, latus rectum = 8</li>
            <li>x²/25 + y²/16 = 1</li>
            <li>c² = 169 − 144 = 25, c = 5, e = 5/13</li>
            <li>x²/9 − y²/16 = 1</li>
            <li>2b²/a = 2(16)/5 = 32/5</li>
          </ol>
        </Expandable>
      </Expandable>

      <Expandable id="h-ex-10-2" title="EXERCISE 10.2">
        <ol>
          <li>Find the equation of the ellipse with latus rectum 8 and eccentricity 3/5.</li>
          <li>Find the equation of the hyperbola with conjugate axis 5 and eccentricity 4/3.</li>
          <li>A point moves so that its distance from (4, 0) is always half its distance from the line x = 16. Find the locus and identify the conic.</li>
          <li>Find the eccentricity of the ellipse x²/6 + y²/2 = 1.</li>
          <li>Find the equation of the parabola whose vertex is the origin and focus is (0, −6).</li>
        </ol>
        <Expandable id="h-ex-10-2-key" title="Answer Key — Exercise 10.2">
          <ol>
            <li>e = 3/5, 2b²/a = 8. From e = c/a = 3/5, c = 3a/5. b² = a² − c² = a² − 9a²/25 = 16a²/25. So 2(16a²/25)/a = 8 → 32a/25 = 8 → a = 25/4. Then b² = 16(25/4)²/25 = 25. Equation: x²/(625/16) + y²/25 = 1.</li>
            <li>2b = 5 → b = 5/2, e = c/a = 4/3. c² = a² + b² → (4a/3)² = a² + 25/4 → 16a²/9 − a² = 25/4 → 7a²/9 = 25/4 → a² = 225/28. Equation: x²/(225/28) − y²/(25/4) = 1.</li>
            <li>√((x−4)² + y²) = |x−16|/2 → 4((x−4)² + y²) = (x−16)² → 3x² + 4y² = 48 → x²/16 + y²/12 = 1. It&apos;s an <strong>ellipse</strong>.</li>
            <li>a² = 6, b² = 2, c² = 4, c = 2. e = 2/√6 = √6/3.</li>
            <li>x² = −24y (opens downward, a = 6).</li>
          </ol>
        </Expandable>
      </Expandable>

      <Expandable id="h-misc-ex-final" title="Miscellaneous Exercise on Chapter 10">
        <ol>
          <li>Find the equation of the circle with centre (1, −2) and passing through the origin.</li>
          <li>Find the equation of the parabola with latus rectum 10 and focus on the negative x-axis.</li>
          <li>Find the eccentricity of the ellipse whose latus rectum is half the major axis.</li>
          <li>Find the equation of the hyperbola with eccentricity 3/2 and conjugate axis 8.</li>
          <li>Find the centre and radius of 2x² + 2y² + 6x − 4y − 7 = 0.</li>
        </ol>
        <Expandable id="h-misc-ex-final-key" title="Answer Key — Miscellaneous Exercise">
          <ol>
            <li>r² = (1−0)² + (−2−0)² = 5. (x − 1)² + (y + 2)² = 5.</li>
            <li>4a = 10 → a = 5/2. Opens left: y² = −10x.</li>
            <li>LR = 2b²/a = a → b² = a²/2. c² = a² − b² = a²/2. e² = 1/2. e = 1/√2.</li>
            <li>e = 3/2, 2b = 8 → b = 4. c = 3a/2. c² = a² + b² → 9a²/4 = a² + 16 → 5a²/4 = 16 → a² = 64/5. Equation: x²/(64/5) − y²/16 = 1.</li>
            <li>Divide by 2: x² + y² + 3x − 2y − 7/2 = 0. g = 3/2, f = −1, c = −7/2. Centre (−3/2, 1). r² = 9/4 + 1 + 7/2 = 9/4 + 4/4 + 14/4 = 27/4. r = 3√3/2.</li>
          </ol>
        </Expandable>
      </Expandable>
    </>
  );
}
